default l0
menu title U-Boot menu
prompt 1
timeout 10

label l0
	menu label Ubuntu 26.04.1 LTS 7.0.0-31-generic
	linux /boot/vmlinuz-7.0.0-31-generic
	initrd /boot/initrd.img-7.0.0-31-generic
	fdtdir /usr/lib/firmware/7.0.0-31-generic/device-tree/
	append root=UUID=320efabb-8ea9-45ee-819c-324fee604ad8 console=ttyS2,1500000n8 quiet splash loglevel=4 rw earlycon=uart8250,mmio32,0xfe660000 consoleblank=0 console=tty1 coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 kasan=off

label l0r
	menu label Ubuntu 26.04.1 LTS 7.0.0-31-generic (rescue target)
	linux /boot/vmlinuz-7.0.0-31-generic
	initrd /boot/initrd.img-7.0.0-31-generic
	fdtdir /usr/lib/firmware/7.0.0-31-generic/device-tree/
	append root=UUID=320efabb-8ea9-45ee-819c-324fee604ad8 console=ttyS2,1500000n8 splash loglevel=4 rw earlycon=uart8250,mmio32,0xfe660000 consoleblank=0 console=tty1 coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 kasan=off single
